defaults: &defaults
  adapter: postgresql
  pool: 5
  connections: 5
  host: localhost
  username: <%= ENV['USER'] %>

development:
  <<: *defaults
  database: valoritization-development

test:
  <<: *defaults
  database: valoritization-test
