default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: valoritization-development
  username: <%= ENV['USER'] %>
  host: localhost

test:
  <<: *defaults
  database: valoritization-test
  username: <%= ENV['USER'] %>
  host: localhost
